# Manifest File to create AWS EKS Cluster in Custom VPC
#
# eksctl create cluster -f eks_cluster_prod.yaml
# eksctl delete cluster -f eks_cluster_prod.yaml

#---------------------------------------------------------------------
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-prod
  region: us-east-1
  version: "1.29"

vpc:
  id: "vpc-0d63da457e9c729ee"
  subnets:
    public:
      us-east-1c: { id: subnet-08c08209732691b71 } # For Load Balancer
      us-east-1a: { id: subnet-09cec82f8ecc1b841 } # For Load Balancer
    private:
      us-east-1b: { id: subnet-0566a858bd3f06fd8 } # For Worker Nodes
      us-east-1d: { id: subnet-0f5acb28def6ee771 } # For Worker Nodes

managedNodeGroups:
  - name: general
    instanceType: t3.medium
    desiredCapacity: 3
    labels: { role: general }
    VolumeSize: 80
    privateNetworking: true # Use Private Subnets
    iam:
      withAddonPolicies:
        imageBuilder: true
